author: ['DoctorReid', '龙女姬']
planet: '仙舟罗浮'
region: '鳞渊境'
floor: 0
tp: '古海宫墟'
route:
  - op: 'move'
    data: [1127, 428]
  - op: 'move'
    data: [1127, 505]
  - op: 'move'
    data: [1147, 505]
  - op: 'move'
    data: [1141, 580]
  - op: 'patrol'
  - op: 'move'
    data: [1145, 607]
  - op: 'patrol'
  - op: 'move'
    data: [1110, 623]
  - op: 'patrol'
  - op: 'move'
    data: [1079, 607]
  - op: 'move'
    data: [1046, 607]
  - op: 'patrol'
  - op: 'move'
    data: [996, 609]
  - op: 'patrol'
  - op: 'move'
    data: [919, 607]
  - op: 'slow_move'
    data: [917, 676]
  - op: 'patrol'
  - op: 'move'
    data: [882, 671]
  - op: 'move'
    data: [843, 638]
  - op: 'move'
    data: [793, 602]
  - op: 'move'
    data: [734, 591]
  - op: 'slow_move'
    data: [711, 585]
  - op: 'patrol'
  - op: 'move'
    data: [692, 549]
  - op: 'patrol'
